/* XPM */
static char * USBdriveconnected_t_xpm[] = {
"16 16 96 2",
"  	c None",
". 	c #F0F0EE",
"+ 	c #F1F1EE",
"@ 	c #F2F2F0",
"# 	c #F3F3F2",
"$ 	c #F4F4F2",
"% 	c #F5F5F4",
"& 	c #F6F8F8",
"* 	c #F4F5F3",
"= 	c #F3F3F0",
"- 	c #F0F0ED",
"; 	c #F8F8F7",
"> 	c #F5F5F5",
", 	c #F6F6F6",
"' 	c #F9F9F9",
") 	c #F4E4D9",
"! 	c #EFD0BD",
"~ 	c #F9F9FA",
"{ 	c #F8F8F8",
"] 	c #F6F6F5",
"^ 	c #FBFBFB",
"/ 	c #FCFCFC",
"( 	c #FCFEFF",
"_ 	c #F1B38F",
": 	c #F1A67A",
"< 	c #FBFBFA",
"[ 	c #FCFCFD",
"} 	c #FDFDFD",
"| 	c #FFFFFF",
"1 	c #FEFFFF",
"2 	c #FADFCE",
"3 	c #F9D4BE",
"4 	c #F4D7C4",
"5 	c #F1CBB2",
"6 	c #E3E3E3",
"7 	c #F3D2BA",
"8 	c #F2C3A2",
"9 	c #F9E1D0",
"0 	c #FAD9C1",
"a 	c #F6B588",
"b 	c #F4A064",
"c 	c #EEEEEE",
"d 	c #F7F7F8",
"e 	c #F9BD8F",
"f 	c #F9B37D",
"g 	c #FADFC9",
"h 	c #FBD8BD",
"i 	c #FAE3D1",
"j 	c #FCE0CA",
"k 	c #FDFDFC",
"l 	c #F1F1F0",
"m 	c #FCEDDF",
"n 	c #FBDABC",
"o 	c #FEE8D5",
"p 	c #F8C291",
"q 	c #F7CDA8",
"r 	c #FCFCFA",
"s 	c #F8F8F9",
"t 	c #FBFFFF",
"u 	c #FAD4AE",
"v 	c #F8C89A",
"w 	c #FCE3C9",
"x 	c #FBFCFD",
"y 	c #FCFBFA",
"z 	c #FCFCFB",
"A 	c #F9F9F8",
"B 	c #E5E5E5",
"C 	c #FBFAF9",
"D 	c #FAFAFB",
"E 	c #FCECDA",
"F 	c #FDDFC2",
"G 	c #FAFAFA",
"H 	c #FAFAF9",
"I 	c #F7F7F6",
"J 	c #EBEBEB",
"K 	c #F9FDFF",
"L 	c #F6C697",
"M 	c #F9C18A",
"N 	c #F8F8F6",
"O 	c #FAF9F8",
"P 	c #F6F9FA",
"Q 	c #FCDAB8",
"R 	c #FDD3AA",
"S 	c #F7F8F9",
"T 	c #FEFEFD",
"U 	c #FDFCFC",
"V 	c #FBFCFC",
"W 	c #A1A2A1",
"X 	c #8DA18B",
"Y 	c #A7B976",
"Z 	c #A7A7A7",
"` 	c #A2A2A2",
" .	c #A9A9A9",
"..	c #A5A6AD",
"+.	c #9AA790",
"@.	c #A8A8A8",
"                                ",
"    . + @ # $ % & * # = . -     ",
"    ; > , ; ' ) ! ~ { ] % ;     ",
"    ^ ^ { / ( _ : < [ ' < ^     ",
"    } { | 1 | 2 3 4 5 | { }     ",
"  6 | { | 7 8 9 0 a b | { | 6   ",
"  c d | 1 e f g h i j k | d c   ",
"  l < } / m n o p q r / } < l   ",
"  s ' / ^ t u v w x y z / A s   ",
"  B , ^ < C D E F G H < ^ I B   ",
"  J { < H H K L M N O H < { J   ",
"  # r H A N P Q R S N A H < #   ",
"  T / U z ^ ^ V V < ^ z z z T   ",
"  W X Y Z Z Z Z Z Z Z Z Z Z `   ",
"   ...+.@.@.@.@.@.@.@.@.@.@. .  ",
"                                "};
