/* XPM */
static char * USBdriveconnected_l_xpm[] = {
"48 48 370 2",
"  	c None",
". 	c #E8E8E7",
"+ 	c #EEEEEE",
"@ 	c #EDEDEC",
"# 	c #ECECEC",
"$ 	c #ECECEB",
"% 	c #EBEBEB",
"& 	c #EBEBEC",
"* 	c #E9E9E8",
"= 	c #EEEEEC",
"- 	c #EFEFED",
"; 	c #F0F0EE",
"> 	c #F1F1EF",
", 	c #F1F1F0",
"' 	c #F2F2F0",
") 	c #F2F2F1",
"! 	c #F2F2EF",
"~ 	c #F2F2F2",
"{ 	c #F3F3F2",
"] 	c #F4F4F2",
"^ 	c #F5F5F3",
"/ 	c #F4F4F3",
"( 	c #F3F3F1",
"_ 	c #ECECEA",
": 	c #F5F5F4",
"< 	c #F6F6F5",
"[ 	c #F7F8F8",
"} 	c #F7F7F6",
"| 	c #F7F7F7",
"1 	c #F8F8F7",
"2 	c #F9F9F9",
"3 	c #F0EEEB",
"4 	c #DEC7B9",
"5 	c #F8F9F9",
"6 	c #B0B0B0",
"7 	c #F7F7F5",
"8 	c #F5F5F5",
"9 	c #F6F6F6",
"0 	c #F8F8F8",
"a 	c #FAFAF9",
"b 	c #FAFAFA",
"c 	c #F4F4F5",
"d 	c #E7B08F",
"e 	c #F19C6A",
"f 	c #EBDAD0",
"g 	c #F9FAFA",
"h 	c #F6F6F4",
"i 	c #C6C6C6",
"j 	c #F9F9F8",
"k 	c #FBFBFB",
"l 	c #E9C7B3",
"m 	c #F19C69",
"n 	c #F29C67",
"o 	c #E9A67D",
"p 	c #F5F2F0",
"q 	c #C6C6C5",
"r 	c #D6D6D5",
"s 	c #FCFCFC",
"t 	c #EDE2DB",
"u 	c #EC9C6C",
"v 	c #F29C69",
"w 	c #F49964",
"x 	c #E1B296",
"y 	c #FAFBFC",
"z 	c #FAFAFB",
"A 	c #D5D5D5",
"B 	c #DFDFDE",
"C 	c #FDFDFE",
"D 	c #F5EEEA",
"E 	c #E89C6F",
"F 	c #F2955D",
"G 	c #F29C68",
"H 	c #F29963",
"I 	c #F2945B",
"J 	c #E7BFA7",
"K 	c #FCFEFF",
"L 	c #F6F6F7",
"M 	c #DEDEDD",
"N 	c #E3E3E2",
"O 	c #FDFDFD",
"P 	c #FCF9F7",
"Q 	c #FDF1E9",
"R 	c #FCF2EB",
"S 	c #F3A677",
"T 	c #F29F6C",
"U 	c #F8D3BC",
"V 	c #FDF2EB",
"W 	c #FCF3ED",
"X 	c #E2E2E2",
"Y 	c #FBFDFE",
"Z 	c #F3A779",
"` 	c #F7D9C7",
" .	c #FDFEFE",
"..	c #FBFCFD",
"+.	c #FCFCFD",
"@.	c #EAEAEA",
"#.	c #FEFEFE",
"$.	c #FFFFFF",
"%.	c #F4AA7A",
"&.	c #F3A26D",
"*.	c #F8DBC8",
"=.	c #F3EAE3",
"-.	c #E7C9B6",
";.	c #E8CBB9",
">.	c #E8CAB8",
",.	c #E8D0C0",
"'.	c #F4F4F4",
").	c #F5AB7B",
"!.	c #F4A36F",
"~.	c #F8DBC9",
"{.	c #F6D9C7",
"].	c #F29E67",
"^.	c #F2A26D",
"/.	c #F2A16C",
"(.	c #F0AA7D",
"_.	c #A7A7A7",
":.	c #F9F5F2",
"<.	c #F4EEEB",
"[.	c #F9F7F5",
"}.	c #F6AE7D",
"|.	c #F5A670",
"1.	c #F8DCC9",
"2.	c #FEFFFF",
"3.	c #F7DBC7",
"4.	c #F5A067",
"5.	c #F5A46D",
"6.	c #F5A36C",
"7.	c #F3AD7D",
"8.	c #A6A6A6",
"9.	c #C1C1C1",
"0.	c #F6F5F4",
"a.	c #E7C1A6",
"b.	c #E5A97F",
"c.	c #E8A678",
"d.	c #E5AE88",
"e.	c #E8D1C0",
"f.	c #FCFFFF",
"g.	c #F6AF7E",
"h.	c #F5A871",
"i.	c #F9DDC9",
"j.	c #F7DAC6",
"k.	c #F5A065",
"l.	c #F5A66E",
"m.	c #F5A46B",
"n.	c #F4AD7C",
"o.	c #C0C0C0",
"p.	c #EEC8AC",
"q.	c #F5A56C",
"r.	c #F6A86F",
"s.	c #F6A76F",
"t.	c #F4A66E",
"u.	c #F2E2D7",
"v.	c #F6B17F",
"w.	c #F6A973",
"x.	c #F8DDCA",
"y.	c #FDFFFF",
"z.	c #FAE4D4",
"A.	c #F8B889",
"B.	c #F6AA73",
"C.	c #F6A870",
"D.	c #F8B381",
"E.	c #F8C29B",
"F.	c #D4D4D4",
"G.	c #DFDFDF",
"H.	c #EFEFEF",
"I.	c #F4B688",
"J.	c #F7AA70",
"K.	c #F7AB72",
"L.	c #F7A96F",
"M.	c #F7D1B4",
"N.	c #F7B481",
"O.	c #F7AD75",
"P.	c #F9DECA",
"Q.	c #FBFBFC",
"R.	c #F7B380",
"S.	c #F7AE77",
"T.	c #FBE6D7",
"U.	c #FEFEFD",
"V.	c #CFCFCF",
"W.	c #EDEDED",
"X.	c #FDFEFF",
"Y.	c #FCDBC2",
"Z.	c #F8AB6F",
"`.	c #F8AE74",
" +	c #F8AE75",
".+	c #F8AC71",
"++	c #F9AF77",
"@+	c #FDF1E7",
"#+	c #FBFDFF",
"$+	c #F9B783",
"%+	c #F8B078",
"&+	c #F9DFCA",
"*+	c #FAF1EA",
"=+	c #F8B47F",
"-+	c #F9B37D",
";+	c #FCEDE1",
">+	c #CECECE",
",+	c #D8D8D8",
"'+	c #F8F8F9",
")+	c #FDFCFB",
"!+	c #FDE2CD",
"~+	c #FAB57D",
"{+	c #FAB278",
"]+	c #FCC69A",
"^+	c #FCFDFD",
"/+	c #FAFCFC",
"(+	c #FAB986",
"_+	c #F9B37A",
":+	c #F9DFCB",
"<+	c #EED7C4",
"[+	c #F9B27A",
"}+	c #FAB882",
"|+	c #FDF9F6",
"1+	c #E4E4E4",
"2+	c #FCFCFB",
"3+	c #FDFDFC",
"4+	c #FBBF8C",
"5+	c #FBB67B",
"6+	c #FAE0C9",
"7+	c #FCFDFE",
"8+	c #FBBD88",
"9+	c #FBB77D",
"0+	c #F6DBC4",
"a+	c #E7E1DD",
"b+	c #DEC3AB",
"c+	c #F5B37B",
"d+	c #FBB579",
"e+	c #FCD7B8",
"f+	c #F3F3F3",
"g+	c #FBCA9E",
"h+	c #FCB87A",
"i+	c #F9D9BB",
"j+	c #FCC089",
"k+	c #FCB97D",
"l+	c #F3B883",
"m+	c #F7B477",
"n+	c #FFB572",
"o+	c #FDC48F",
"p+	c #FDDFC3",
"q+	c #DBDBDA",
"r+	c #FDDDBE",
"s+	c #FFBC7C",
"t+	c #F3C89E",
"u+	c #FEC48D",
"v+	c #FFBD7F",
"w+	c #FFC289",
"x+	c #FED8B3",
"y+	c #FEEEDF",
"z+	c #FDF9F5",
"A+	c #FCFDFC",
"B+	c #FFFFFE",
"C+	c #DADADA",
"D+	c #FCF9F6",
"E+	c #FFC284",
"F+	c #FFBE7D",
"G+	c #E4BE9A",
"H+	c #E4DDD6",
"I+	c #F3F1EF",
"J+	c #FEC58C",
"K+	c #FFC083",
"L+	c #FBE7D3",
"M+	c #FBFBFA",
"N+	c #FDEFE1",
"O+	c #FFD0A1",
"P+	c #FFBD79",
"Q+	c #FCBA79",
"R+	c #EEBD8C",
"S+	c #FDBF82",
"T+	c #FEC082",
"U+	c #FAE4CD",
"V+	c #FBFCFB",
"W+	c #F1F1F1",
"X+	c #FCFAF6",
"Y+	c #FDF2E7",
"Z+	c #FFDDBC",
"`+	c #FFC68D",
" @	c #FFBF80",
".@	c #9E9E9E",
"+@	c #FAFCFD",
"@@	c #FAFEFF",
"#@	c #FEC68E",
"$@	c #FAE3CD",
"%@	c #F0F0EF",
"&@	c #BBBBBB",
"*@	c #F0F0F0",
"=@	c #F8F9FA",
"-@	c #FEC58D",
";@	c #FAFBFA",
">@	c #F9FBFB",
",@	c #FBE4CE",
"'@	c #FAFBFB",
")@	c #D7D7D7",
"!@	c #E5DBD1",
"~@	c #FBC087",
"{@	c #FFBF81",
"]@	c #EBCBAB",
"^@	c #F0EDE9",
"/@	c #F9FAF9",
"(@	c #C5C5C5",
"_@	c #EBD6C0",
":@	c #FBBB7D",
"<@	c #FFBF7F",
"[@	c #FFBE7C",
"}@	c #F0BE8E",
"|@	c #F2F0EC",
"1@	c #C4C4C4",
"2@	c #D1D1D1",
"3@	c #F8FBFD",
"4@	c #FAC189",
"5@	c #FFBD7C",
"6@	c #F8DFC7",
"7@	c #F8FAFB",
"8@	c #E0E0E0",
"9@	c #FCFCFA",
"0@	c #F7F9FA",
"a@	c #FED0A3",
"b@	c #FFBD7D",
"c@	c #FAEBDB",
"d@	c #E0E0DF",
"e@	c #F8F8F6",
"f@	c #F6F7F6",
"g@	c #F9F1E9",
"h@	c #FFD0A3",
"i@	c #FFC183",
"j@	c #FFC78F",
"k@	c #FDDFC2",
"l@	c #F7F8F9",
"m@	c #EAEAE9",
"n@	c #F7F5F1",
"o@	c #FAF3EC",
"p@	c #FBF3EB",
"q@	c #F8F3EE",
"r@	c #FDFDFB",
"s@	c #F9F9F7",
"t@	c #EFEFEE",
"u@	c #9D9D9D",
"v@	c #B3B3B3",
"w@	c #B1B1B1",
"x@	c #B1B0B1",
"y@	c #ADAEAE",
"z@	c #9A9A9A",
"A@	c #A3A3A3",
"B@	c #A2A2A2",
"C@	c #A3A0A4",
"D@	c #6A946C",
"E@	c #69B036",
"F@	c #899F80",
"G@	c #A2A1A2",
"H@	c #A5A5A5",
"I@	c #B7B7B7",
"J@	c #B6B6B6",
"K@	c #B7B1BB",
"L@	c #57B425",
"M@	c #C8F91F",
"N@	c #A4C75D",
"O@	c #B5B4B6",
"P@	c #AEAEAE",
"Q@	c #CDCDCD",
"R@	c #CBCBCB",
"S@	c #CDCBCD",
"T@	c #A5C4AC",
"U@	c #A0D65E",
"V@	c #C2CBB9",
"W@	c #CBCBCC",
"X@	c #8C8C8C",
"Y@	c #838383",
"Z@	c #848484",
"`@	c #868486",
" #	c #87838C",
".#	c #848485",
"                                                                                                ",
"                                                                                                ",
"            . + @ @ # $ $ $ $ % & % $ $ $ $ $ $ $ $ $ $ $ % % % $ $ $ $ $ # @ @ + .             ",
"            * = = = = - - ; > > , ' ' ' ' ) ) ) ) ) ) ' ' ' ' > > > ; - = = = = = *             ",
"            $ - - ; > ! ' ' ) ~ { ] ) { ] ^ ^ ^ ^ ^ / ] { ) ] { ) ( ' ' , ; ; - = _             ",
"            > > , ' ) { { / ^ : : { : < < < < < [ < < < < : { : ^ / ] { ( ' ' > ; ;             ",
"            ( ) ( { / / : : < < / } } | | 1 2 3 4 5 | | | } } / < < : ^ / ] ( ) ' )             ",
"          6 7 ] / : 8 < 9 1 < : 0 0 2 2 a b c d e f g 2 2 2 0 0 : < | } < h : / ] < 6           ",
"          i } : < } | 0 j 1 8 b b k k k k b l m n o p k k k k b b : | 0 1 } } < : 7 q           ",
"          r 1 } 1 0 2 2 b 8 b k k k k k s t u v v w x y k k k k k z 8 a 2 j 1 | } 1 A           ",
"          B j 0 2 b k k 9 0 s s k s s C D E F G v H I J K s s k s s 0 L k b b 2 0 j M           ",
"          N b b k k k 2 8 s s s s O O O P Q R S T U V W O O O s s s s 8 2 k k k b b X           ",
"          % s k k k s ~ O O O O O O O O O O Y Z T `  .O ........+.O s O ~ s k k k k @.          ",
"          8 k s s s | 2 O O #.O #.#.#.#.#.$.K %.&.*.$.=.-.;.;.>.,.$.O O 2 | s s s k '.          ",
"          2 s s O s 8 s #.#.#.#.#.#.#.#.#.#.K ).!.~.$.{.].^.^./.(.$.#.#.s 8 s O s s 2           ",
"        _.~ s O O b 9 #.#.#.#.#.k :.<.[.O #.K }.|.1.2.3.4.5.5.6.7.$.#.#.#.9 b O O s ~ 8.        ",
"        9.9 O O $.~ O #.#.#.#.0.a.b.c.d.e.f. .g.h.i.$.j.k.l.l.m.n.$.#.#.#.O ~ #.O O 8 o.        ",
"        A 0 #.#.$.+ $.#.#.#.$.p.q.r.r.s.t.u.f.v.w.x.y.z.A.B.C.D.E.2.#.#.#.$.+ $.#.#.0 F.        ",
"        G.k #.$.H.O #.#.#.#.2.I.J.K.K.K.L.M.f.N.O.P. .y.Q.R.S.T.2.U.#.#.#.#.O H.$.#.k G.        ",
"        V.s #.$.W.$.#.#.O O X.Y.Z.`. +.+++@+#+$+%+&+ .O *+=+-+;+C O O O U.#.$.W.$.#.s >+        ",
"        ,+O #.9 '+U.O O O O O )+!+~+{+]+@+^+/+(+_+:+ .y.<+[+}+|+O O O O O U.U.'+9 #.O ,+        ",
"        1+#.#./ 2+O O O O 3+3+3+y.4+5+6+7+s y 8+9+0+a+b+c+d+e+y.3+3+3+O O O O 2+/ #.#.1+        ",
"        H.#.U.f+k O O O 3+s s s f.g+h+i+s s y j+k+l+m+n+o+p+K s s 3+s 3+O O O k / U.#.H.        ",
"        q+#.k '.O 3+3+s s s s 2+K r+s+t+j U.y u+v+w+x+y+z+A+2+2+2+s s s s 3+3+O '.k B+C+        ",
"        X #.k / 3+3+s s s 2+2+2+s D+E+F+G+H+I+J+K+L+#+Q.k k 2+2+2+2+2+s s s 3+3+'.k #.X         ",
"        % C M+'.3+s s s 2+2+k k k ..N+O+P+Q+R+S+T+U+V+M+M+k M+k k 2+2+2+s s s 3+: M+C %         ",
"        W+U.{ b s 2+2+2+k k M+M+M+M+k X+Y+Z+`+ @T+U+V+M+M+M+M+M+M+k k 2+2+2+s s b { U.W+        ",
"      .@0 U.H.O 2+2+2+k k M+M+M+M+M+M+b b +@@@#@T+$@z b b M+M+M+M+M+M+k k 2+2+s O %@U.1 .@      ",
"      &@a O *@3+2+k k k M+M+M+b a b a a a a =@-@T+$@;@a a a a M+b M+M+M+k k k 2+3+*@O b &@      ",
"      >+s O ) 3+k k M+M+M+M+a a a a a a a a >@-@T+,@'@a a a a a a b M+M+M+M+k k 3+) O s >+      ",
"      )@#.3+) s k M+M+M+b a a a a a a a j < !@~@{@]@^@/@a a a a a a a M+M+M+M+k s ) 3+#.)@      ",
"      (@$.M+'.k M+M+M+b a a a a j a j j g _@:@<@ @[@}@|@/@j a a a a a a b M+M+M+k '.M+$.1@      ",
"      2@B+| 0 M+M+M+b a a a a j j 1 1 1 3@4@<@ @ @ @5@6@7@1 j j j a a a a b M+M+M+0 | B+2@      ",
"      8@U.'.9@M+M+b a a a j j j 1 1 1 } 0@a@b@ @ @<@F+c@5 1 1 1 j j a a a a b M+M+9@'.U.d@      ",
"      @.O : M+M+b a a a j j j 1 e@e@} 7 f@g@h@i@5@j@k@l@7 } e@1 1 j j j a a a b M+M+: O m@      ",
"      , s < M+M+a a a j j 1 1 } } 7 < < h h n@o@p@q@h < < < 7 } e@1 j j j a a a M+M+< s ,       ",
"      8 2+} M+a a a j j 1 1 } } < < < : : : : : : : : : h < < < } e@1 j j a a a a M+} 2+8       ",
"      a r@3+k M+M+M+a j j 1 e@7 < h : : ^ ^ ^ / / ^ ^ ^ : : h 7 } 1 s@j j a M+M+M+2+3+3+b       ",
"      % % % # @ W.+ + t@%@*@*@*@W+~ ~ ~ f+f+f+f+f+f+f+f+~ ~ W+W+*@*@H.%@t@+ + W.@ # % % %       ",
"      u@v@w@w@w@x@y@x@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@w@v@u@      ",
"      z@A@B@B@C@D@E@F@G@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@A@z@      ",
"      H@I@J@J@K@L@M@N@O@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@J@I@H@      ",
"      P@Q@R@R@S@T@U@V@W@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@R@Q@P@      ",
"      z@X@Y@Z@Z@`@ #.#Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Z@Y@X@z@      ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
